insert into cat_estados (nombre) VALUES ('Aguascalientes');
insert into cat_estados (nombre) VALUES ('Baja California');
insert into cat_estados (nombre) VALUES ('Baja California Sur');
insert into cat_estados (nombre) VALUES ('Campeche');
insert into cat_estados (nombre) VALUES ('Coahuila de Zaragoza');
insert into cat_estados (nombre) VALUES ('Colima');
insert into cat_estados (nombre) VALUES ('Chiapas');
insert into cat_estados (nombre) VALUES ('Chihuahua');
insert into cat_estados (nombre) VALUES ('Ciudad de México');
insert into cat_estados (nombre) VALUES ('Durango');
insert into cat_estados (nombre) VALUES ('Guanajuato');
insert into cat_estados (nombre) VALUES ('Guerrero');
insert into cat_estados (nombre) VALUES ('Hidalgo');
insert into cat_estados (nombre) VALUES ('Jalisco');
insert into cat_estados (nombre) VALUES ('México');
insert into cat_estados (nombre) VALUES ('Michoacán de Ocampo');
insert into cat_estados (nombre) VALUES ('Morelos');
insert into cat_estados (nombre) VALUES ('Nayarit');
insert into cat_estados (nombre) VALUES ('Nuevo León');
insert into cat_estados (nombre) VALUES ('Oaxaca');
insert into cat_estados (nombre) VALUES ('Puebla');
insert into cat_estados (nombre) VALUES ('Querétaro');
insert into cat_estados (nombre) VALUES ('Quintana Roo');
insert into cat_estados (nombre) VALUES ('San Luis Potosí');
insert into cat_estados (nombre) VALUES ('Sinaloa');
insert into cat_estados (nombre) VALUES ('Sonora');
insert into cat_estados (nombre) VALUES ('Tabasco');
insert into cat_estados (nombre) VALUES ('Tamaulipas');
insert into cat_estados (nombre) VALUES ('Tlaxcala');
insert into cat_estados (nombre) VALUES ('Veracruz de Ignacio de la Llave');
insert into cat_estados (nombre) VALUES ('Yucatán');
insert into cat_estados (nombre) VALUES ('Zacatecas');
